services:
  db:
    image: postgres:17-alpine
    container_name: academyQuest_db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - academyQuest_data:/var/lib/postgresql/data

volumes:
  academyQuest_data: